[package]
name = "substreams-tron-proto"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build = "0.13"