// @generated
// This file is @generated by prost-build.
/// key = <bytes pair>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PairCreated {
    /// log.address - the factory that created the pair
    #[prost(bytes="vec", tag="1")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
}
/// key = <bytes exchange>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewExchange {
    /// log.address - the factory that created the pair
    #[prost(bytes="vec", tag="1")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
