// @generated
// This file is @generated by prost-build.
/// key = <1-byte prefix of Keys enum> + <pair bytes>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PairCreated {
    #[prost(bytes="vec", tag="1")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Keys {
    StoreTypeUnspecified = 0,
    PairCreated = 1,
}
impl Keys {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Keys::StoreTypeUnspecified => "STORE_TYPE_UNSPECIFIED",
            Keys::PairCreated => "PAIR_CREATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STORE_TYPE_UNSPECIFIED" => Some(Self::StoreTypeUnspecified),
            "PAIR_CREATED" => Some(Self::PairCreated),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
