// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="10")]
        TokenExchange(super::TokenExchange),
        #[prost(message, tag="11")]
        AddLiquidity(super::AddLiquidity),
        #[prost(message, tag="12")]
        RemoveLiquidity(super::RemoveLiquidity),
        #[prost(message, tag="13")]
        RemoveLiquidityOne(super::RemoveLiquidityOne),
        #[prost(message, tag="14")]
        RemoveLiquidityImbalance(super::RemoveLiquidityImbalance),
        #[prost(message, tag="15")]
        CommitNewAdmin(super::CommitNewAdmin),
        #[prost(message, tag="16")]
        NewAdmin(super::NewAdmin),
        #[prost(message, tag="17")]
        CommitNewFee(super::CommitNewFee),
        #[prost(message, tag="18")]
        NewFee(super::NewFee),
        #[prost(message, tag="19")]
        RampA(super::RampA),
        #[prost(message, tag="20")]
        StopRampA(super::StopRampA),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenExchange {
    #[prost(bytes="vec", tag="1")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    /// int128
    #[prost(string, tag="2")]
    pub sold_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub tokens_sold: ::prost::alloc::string::String,
    /// int128
    #[prost(string, tag="4")]
    pub bought_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub tokens_bought: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256[3]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256[3]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub invariant: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256[3]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256[3]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityOne {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub coin_amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityImbalance {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256[3]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256[3]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub invariant: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitNewAdmin {
    /// uint256
    #[prost(string, tag="1")]
    pub deadline: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewAdmin {
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitNewFee {
    /// uint256
    #[prost(string, tag="1")]
    pub deadline: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub admin_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewFee {
    /// uint256
    #[prost(string, tag="1")]
    pub fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub admin_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RampA {
    /// uint256
    #[prost(string, tag="1")]
    pub old_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub new_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub initial_time: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub future_time: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopRampA {
    /// uint256
    #[prost(string, tag="1")]
    pub a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub t: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolInfo {
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub total_liquidity: ::prost::alloc::string::String,
}
